### ISSUE TITLE
Añadir un footer global al sitio web

### ISSUE THREAD

**Issue by yohanvillarp** [yohanvillarp/Seidel-project#2]
# Añadir un footer global al sitio web

Se requiere agregar un footer que se muestre en la parte inferior de cada página, con las siguientes secciones:

## Secciones del Footer:
- **Empresa**: 
  - Nosotros
  - Nuestros servicios
  - Políticas de privacidad
- **Ayuda**: 
  - Preguntas frecuentes
  - Compras y eventos
- **Síguenos**: 
  - Redes sociales

Es importante que el footer sea **responsivo** y se adapte correctamente a dispositivos móviles, además se debe usar la metodología BEM para la elaboración del diseño.

## Tareas:
1. Crear un componente `Footer` en React.
2. Estilizar el footer con CSS para que sea visualmente atractivo.
3. Asegurarse de que el footer se vea correctamente en todas las páginas del sitio.

## Consideraciones adicionales:
El footer debe ser coherente en todas las páginas del sitio, garantizando una navegación intuitiva y accesible para los usuarios.
#### Redes sociales
instagram : https://www.instagram.com/seidel_store/
x : https://x.com/vihukstore
facebook: https://www.facebook.com/profile.php?id=61566807050447

## Imagen de referencia
![image](https://github.com/user-attachments/assets/fe8d302c-89ad-4052-86d8-87c83bb6fd6b)

**Comment by joseantoniohg26** [comment]
Ya termine el issue
